development:
  username: username
  password: 5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8
  api_key: apisalt
  db:
    name: db/development.tch
    

deployment:
  username: drodriguez
  password: 5defdd0ff7c026d56aff770456e9d57785feafa8
  api_key: 10d7e2a118d6120cb3102f8ec5431810
  db:
    name: db/deployment.tch
    
test:
  username: username
  password: 5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8
  api_key: apisalt
  db:
    name: *
